name: 'pinterest'
version: '0.12.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  pinterest:
    +schema: pinterest
    +materialized: table
vars:
  pinterest:
    ad_group_history: "{{ ref('stg_pinterest_ads__ad_group_history') }}"
    ad_group_report: "{{ ref('stg_pinterest_ads__ad_group_report') }}"
    advertiser_history: "{{ ref('stg_pinterest_ads__advertiser_history') }}"
    advertiser_report: "{{ ref('stg_pinterest_ads__advertiser_report') }}"
    campaign_history: "{{ ref('stg_pinterest_ads__campaign_history') }}"
    campaign_report: "{{ ref('stg_pinterest_ads__campaign_report') }}"
    keyword_history: "{{ ref('stg_pinterest_ads__keyword_history') }}"
    keyword_report: "{{ ref('stg_pinterest_ads__keyword_report') }}"
    pin_promotion_history: "{{ ref('stg_pinterest_ads__pin_promotion_history') }}"
    pin_promotion_report: "{{ ref('stg_pinterest_ads__pin_promotion_report') }}"
    pin_promotion_targeting_report: "{{ ref('stg_pinterest_ads__pin_promotion_targeting_report') }}"
    targeting_geo: "{{ ref('stg_pinterest_ads__targeting_geo') }}"
    targeting_geo_region: "{{ ref('stg_pinterest_ads__targeting_geo_region') }}"
    pinterest__ad_group_report_passthrough_metrics: []
    pinterest__advertiser_report_passthrough_metrics: []
    pinterest__campaign_report_passthrough_metrics: []
    pinterest__keyword_report_passthrough_metrics: []
    pinterest__pin_promotion_report_passthrough_metrics: []
    pinterest__pin_promotion_targeting_report_passthrough_metrics: []
