name: 'pinterest'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  pinterest:
    +schema: pinterest
    +materialized: table
    intermediate:
      +materialized: ephemeral

vars:
  pinterest: 
    pin_promotion_report: "{{ ref('stg_pinterest_ads__pin_promotion_report') }}"
    ad_group_history: "{{ ref('stg_pinterest_ads__ad_group_history') }}"
    campaign_history: "{{ ref('stg_pinterest_ads__campaign_history') }}"
    pin_promotion_history: "{{ ref('stg_pinterest_ads__pin_promotion_history') }}"
  pin_promotion_report_pass_through_metric: []
  dbt_utils_dispatch_list: ['spark_utils', 'fivetran_utils']
  fivetran_utils_dispatch_list: ['spark_utils']
