name: 'pinterest_integration_tests'
version: '0.11.0'
profile: 'integration_tests'
config-version: 2

vars:
  pinterest_schema: pinterest_integration_tests_6
  pinterest_ads_ad_group_history_identifier: "pinterest_ad_group_history_data"
  pinterest_ads_campaign_history_identifier: "pinterest_campaign_history_data"
  pinterest_ads_pin_promotion_history_identifier: "pinterest_pin_promotion_history_data"
  pinterest_ads_pin_promotion_report_identifier: "pinterest_pin_promotion_report_data"
  pinterest_ads_keyword_history_identifier: "pinterest_keyword_history_data"
  pinterest_ads_keyword_report_identifier: "pinterest_keyword_report_data"
  pinterest_ads_ad_group_report_identifier: "pinterest_ad_group_report_data"
  pinterest_ads_campaign_report_identifier: "pinterest_campaign_report_data"
  pinterest_ads_advertiser_history_identifier: "pinterest_advertiser_history_data"
  pinterest_ads_advertiser_report_identifier: "pinterest_advertiser_report_data"

  # pinterest__ad_group_report_passthrough_metrics: 
  #   - name: "total_conversions"
  #   - name: "total_view_checkout"
  #     alias: "t_view_checkout"

models:
  +schema: "pinterest_ads_{{ var('directed_schema','dev') }}"

seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  pinterest_integration_tests:
    +column_types:
        id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        campaign_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        ad_group_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        pin_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        campaign_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        ad_account_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        advertiser_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        pin_promotion_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        keyword_id: "{{ 'varchar(500)' if target.type in ('redshift','postgres') else 'string'}}"
        spend_in_micro_dollar: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        total_conversions_value_in_micro_dollar: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
