name: 'pinterest_integration_tests'
version: '0.9.0'
profile: 'integration_tests'
config-version: 2

vars:
  pinterest_schema: pinterest_integration_tests_3
  pinterest_ad_group_history_identifier: "pinterest_ad_group_history_data"
  pinterest_campaign_history_identifier: "pinterest_campaign_history_data"
  pinterest_pin_promotion_history_identifier: "pinterest_pin_promotion_history_data"
  pinterest_pin_promotion_report_identifier: "pinterest_pin_promotion_report_data"
  pinterest_keyword_history_identifier: "pinterest_keyword_history_data"
  pinterest_keyword_report_identifier: "pinterest_keyword_report_data"
  pinterest_ad_group_report_identifier: "pinterest_ad_group_report_data"
  pinterest_campaign_report_identifier: "pinterest_campaign_report_data"
  pinterest_advertiser_history_identifier: "pinterest_advertiser_history_data"
  pinterest_advertiser_report_identifier: "pinterest_advertiser_report_data"

seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  pinterest_integration_tests:
    +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        pin_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ad_account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        advertiser_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        pin_promotion_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        keyword_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
