name: 'pinterest_integration_tests'
version: '0.5.1'
profile: 'integration_tests'
config-version: 2

vars:
  pinterest_source:
    ad_group_history: "{{ ref('ad_group_history_data') }}"
    campaign_history: "{{ ref('campaign_history_data') }}"
    pin_promotion_history: "{{ ref('pin_promotion_history_data') }}"
    pin_promotion_report: "{{ ref('pin_promotion_report_data') }}"
    advertiser_history: "{{ ref('advertiser_history_data') }}"

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  pinterest_integration_tests:
    ad_group_history_data:
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        CAMPAIGN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    campaign_history_data:
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ADVERTISER_ID: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
    pin_promotion_history_data:
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        AD_GROUP_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        PIN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    pin_promotion_report_data:
      +column_types:
        PIN_PROMOTION_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        AD_GROUP_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        CAMPAIGN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ADVERTISER_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    advertiser_history_data:
      +column_types:
        id: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
        owner_user_id: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
